---
plugin: aws_ec2
regions:
  - "eu-central-1"
filters:
  instance-state-name: running
  tag:Name: fabio-dev
  tag:Environment: dev
  tag:ostype: linux
compose:
  private_ip_address: private_ip_address
hostnames:
  - private-ip-address