---
- name: Deploy workoutrecorder backend
  hosts: all
  become: true
  roles:
    
    - role: prerequisites
      tags:
        - prerequisites
        
    - role: consul
      tags:
        - consul

    - role: fabio
      tags:
        - fabio
